version: '3'

services:
  rsshub:
    image: diygod/rsshub
    container_name: rsshub
    restart: always
    ports:
        - '1200:1200'
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
      PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
    labels:
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - redis
      - browserless

  browserless:
    image: browserless/chrome
    container_name: browserless
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ./redis-data:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true