version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: host
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
    command:
      [
        "-i",
        "30",
        "--cleanup",
        "--label-enable"
      ]
