version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: host
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
    command:
      [
        "--interval",
        "30",
        "ttrss",
        "nodered",
        "nginxproxymanager",
        "portainer",
        "unlockmusic",
        "mercury",
        "postgres",
        "opencc",
        "adguardhome",
        "jellyfin",
      ]
