version: "3"

services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: always
    network_mode: host # 1880:1880
    volumes:
      - ./data:/data
    environment: 
      - TZ=Europe/Berlin
