version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      - ./conf:/etc/nginx
      - ./www:/var/www
    environment:
      - TZ=Europe/Berlin
    logging: 
      driver: "json-file"
      options: 
        max-size: "1g"
    labels:
      - sh.acme.autoload.domain=awyun.top
      - com.centurylinklabs.watchtower.enable=true

  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    network_mode: host
    command: daemon
    restart: always
    volumes:
      - ./acme.sh:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: 
      - .env
    labels: 
      - com.centurylinklabs.watchtower.enable=true