version: "3"
services:
  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    restart: always
    ports:
      - 9887:80
    environment:
      - SELF_URL_PATH=https://rss.awyun.top/ # please change to your own domain
      - DB_PASS=ttrss
      - ENABLE_PLUGINS=auth_internal,fever,mercury_fulltext,opencc
      - SINGLE_USER_MODE=false
      - FEED_LOG_QUIET=true
    networks:
      - public_access
      - service_only
      - database_only
    stdin_open: true
    tty: true
    labels:
      - com.centurylinklabs.watchtower.enable=true

  service.mercury: # service.mercury:3000
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    restart: always
    networks:
      - service_only
    labels:
      - com.centurylinklabs.watchtower.enable=true

  service.opencc: # service.opencc:3000
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - service_only
    labels:
      - com.centurylinklabs.watchtower.enable=true      

  database.postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=ttrss
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
    networks:
      - database_only
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  public_access: # Provide the access for ttrss UI
  service_only: # Provide the communication network between services only
    internal: true
  database_only: # Provide the communication between ttrss and database only
    internal: true