version: "3"
services:
  
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    network_mode: host # 9000:9000 8000:8000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    environment: 
      - TZ=Europe/Berlin
    labels:
      - com.centurylinklabs.watchtower.enable=true
