version: "3"
services:
  tmm:
    image: romancin/tinymediamanager:latest-v4
    container_name: tmm
    restart: always
    ports:
      - 5900:5900
      - 5800:5800
    volumes:
      - ./config:/config:rw
      - /mnt/video:/media:rw
    environment:
      - TZ=Europe/Berlin
      - USER_ID=0
      - GROUP_ID=0
      - ENABLE_CJK_FONT=1
    labels:
      - com.centurylinklabs.watchtower.enable=true
